# 추출된 KG의 사실성 검증 (hallucination check).
# Gemini + Google Search grounding으로 외부 사실과 비교 — transcript에 없다고 hallucination 아님 (강의는 일부만 다룸)
import json
import os
import re

from google import genai

GEMINI_MODEL = "gemini-2.5-flash"

SYSTEM_PROMPT = """\
You are a FACTUAL CORRECTNESS auditor for a lecture knowledge graph.

The knowledge graph below was extracted from a university lecture by an
automated LLM pipeline. Some fields were extracted directly from the
transcript; others were generated by a separate enrichment LLM step.
Your job is to flag content that is **factually wrong about the world**,
using Google Search to verify when you are uncertain.

DEFINITION OF HALLUCINATION (used here)
  A field is hallucinated when its assertion is incorrect in the relevant
  academic / technical literature — i.e., a domain expert reading a
  textbook would say "no, that is wrong."

NOT A HALLUCINATION
  • A claim that is factually correct but absent from the lecture transcript.
    (Lectures cover only a slice of a subject; omission ≠ error.)
  • Different wording that preserves meaning.
  • A soft / inferred edge whose inference is reasonable, even if the
    transcript does not literally say it.
  • Pedagogical simplification that is technically imprecise but standard
    at an introductory level (mark as severity "low" only if misleading).

WHAT TO CHECK

  Per node:
    - `label`                       Is this a real concept? Is the term
                                    used correctly?
    - `description` (enrichment)    Are the factual claims accurate?
    - `why_it_matters` (enrichment) Are the factual claims accurate?

  Per edge:
    - `relation_type` (explains | motivates | contrasts | requires |
                      example_of | elaborates)
                                    Is this relation factually appropriate
                                    between these two concepts? E.g. saying
                                    A "motivates" B when in reality B
                                    historically preceded A would be wrong.
    - `reason` (enrichment)         Is the explanation factually accurate?

USE GOOGLE SEARCH WHEN
  • You are not confident a claim is correct from your own knowledge.
  • A specific date, number, definition, or attribution is asserted.
  • The lecture domain is specialised (distributed systems, info theory,
    formal logic, databases, etc.).

DO NOT USE SEARCH FOR
  • Trivially obvious truths.
  • Pedagogical framings that aren't factual claims.

OUTPUT — strict JSON, exactly this shape:
{
  "summary": "Brief overall assessment (1-2 sentences)",
  "total_nodes_checked": <int>,
  "total_edges_checked": <int>,
  "issues_found": <int>,
  "issues": [
    {
      "type": "node_label" | "node_description" | "node_why_it_matters" |
              "edge_relation" | "edge_reason",
      "id": "<node_id>" | "<src_id> -> <tgt_id>",
      "label": "<node label or relation_type>",
      "issue": "factually_incorrect" | "misuse_of_term" |
               "wrong_relationship" | "misleading_simplification",
      "explanation": "1-2 sentences naming the specific factual error",
      "correction": "What the correct fact is (if known)",
      "severity": "high" | "medium" | "low",
      "sources": ["<URL or citation>", ...]
    }
  ]
}

If everything checks out, return an empty `issues` list with a positive summary.
"""


# 외부에서 부르는 진입점: kg dict 받아서 issue list 반환
def check_hallucinations(kg, transcript=""):
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        raise ValueError(
            "GEMINI_API_KEY or GOOGLE_API_KEY environment variable is required. "
            "Get one at https://aistudio.google.com/apikey"
        )

    nodes = kg.get("nodes", [])
    edges = kg.get("edges", [])
    kg_summary = _format_kg_for_prompt(nodes, edges)

    transcript_block = ""
    if transcript and transcript.strip():
        snippet = transcript[:8000]
        transcript_block = (
            "## Lecture Domain Context (use only to identify the subject area, "
            "NOT as a ground-truth filter)\n"
            f"{snippet}\n\n"
        )

    user_prompt = f"""\
{transcript_block}## Knowledge Graph
{kg_summary}

Audit each node and edge for factual correctness. Use Google Search when
you are not confident. Do NOT flag content merely for being absent from
the transcript — only flag content that is factually wrong about the world.
"""

    client = genai.Client(api_key=api_key)

    try:
        tools = [genai.types.Tool(google_search=genai.types.GoogleSearch())]
    except Exception:
        tools = None

    last_err = None
    raw_text = ""
    result = None
    for _ in range(2):
        try:
            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=user_prompt,
                config=genai.types.GenerateContentConfig(
                    system_instruction=SYSTEM_PROMPT,
                    temperature=0.1,
                    tools=tools,
                ),
            )
            raw_text = response.text or ""
            result = _extract_json(raw_text)
            if result is not None:
                break
        except Exception as e:
            last_err = e
            continue

    if result is None:
        raise RuntimeError(
            f"Failed to parse Gemini response after retry: {last_err}\nRaw: {raw_text[:500]}"
        )

    result.setdefault("summary", "Check completed.")
    result.setdefault("total_nodes_checked", len(nodes))
    result.setdefault("total_edges_checked", len(edges))
    result.setdefault("issues", [])
    result.setdefault("issues_found", len(result["issues"]))
    return result


_JSON_BLOCK_RE = re.compile(r"\{.*\}", re.DOTALL)


def _extract_json(text):
    if not text:
        return None
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    if fenced:
        try:
            return json.loads(fenced.group(1))
        except json.JSONDecodeError:
            pass
    m = _JSON_BLOCK_RE.search(text)
    if m:
        try:
            return json.loads(m.group(0))
        except json.JSONDecodeError:
            return None
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return None


def _edge_is_grounded(e):
    src = e.get("edge_source")
    if src == "explicit":
        return True
    if src == "inferred":
        return False
    return "confidence_score" not in e


# LLM 프롬프트용 텍스트 포맷. 추출 단계 vs enrichment 단계 출처 표시해서 audit이 구분하게
def _format_kg_for_prompt(nodes, edges):
    lines = []
    lines.append("### Nodes")
    lines.append("(label = extracted; description / why_it_matters = enrichment LLM)")
    for n in nodes:
        nid = n.get("id") or n.get("node_id") or "?"
        label = n.get("label", "?")
        backbone = " [BACKBONE]" if n.get("is_backbone") else ""
        anchor = n.get("slide_anchor_title") or n.get("slide_anchor_id") or ""
        anchor_str = f"  (anchor: {anchor})" if anchor else ""
        desc = n.get("description", "")
        why = n.get("why_it_matters", "")
        ntype = n.get("node_type", "concept")

        lines.append(f"- {nid}: {label}{backbone}  ({ntype}){anchor_str}")
        if desc:
            lines.append(f"  [enrichment] description: {desc}")
        if why:
            lines.append(f"  [enrichment] why_it_matters: {why}")

    grounded = [e for e in edges if _edge_is_grounded(e)]
    soft = [e for e in edges if not _edge_is_grounded(e)]

    lines.append("\n### Edges — Grounded (explicit)")
    lines.append("(relation_type / justification = extracted; reason = enrichment LLM)")
    if not grounded:
        lines.append("(none)")
    for e in grounded:
        lines.append(_format_edge(e))

    lines.append("\n### Edges — Soft (inferred from lecture flow)")
    lines.append("(treat the inference as legitimate unless factually wrong)")
    if not soft:
        lines.append("(none)")
    for e in soft:
        lines.append(_format_edge(e))

    return "\n".join(lines)


def _format_edge(e):
    src = e.get("source") or e.get("source_id") or e.get("from") or "?"
    tgt = e.get("target") or e.get("target_id") or e.get("to") or "?"
    rel = e.get("relation") or e.get("relation_type") or e.get("edge_type") or "?"
    reason = e.get("reason") or ""
    conf = e.get("confidence_score")

    head = f"- {src} --[{rel}]--> {tgt}"
    if conf is not None:
        head += f"  (confidence: {conf})"
    if reason:
        head += f"\n  [enrichment] reason: {reason}"
    return head
